### ISSUE TITLE
Support [NotMapped] attribute

### ISSUE THREAD

**Issue by justdmitry** [cdemi/SimpleSqlBulkCopy#5]
Entity class properties, marked with `[NotMapped]` attribute, should be skipped, because they are not mapped to DB.

**Comment by cdemi** [comment]
Are you able to do a pull request for this?
________________________________

**Comment by justdmitry** [comment]
Sorry, no. It's faster for me to copy/use your code, because I need to skip virtual properties (that's EF stuff for table references), also I got [Nullable<T> issue](https://stackoverflow.com/questions/23233295/dataset-does-not-support-system-nullable-in-export), null/DBNull issue and may be more (I have only half of my tables converted).
